services:
  adminer:
    container_name: adminer
    image: adminer
    restart: on-failure
    environment:
      - ADMINER_DESIGN=pepa-linha
    ports:
      - "8081:8080"
    depends_on:
      - database
    networks:
      - network

  database:
    image: postgres:16.2-alpine
    restart: always
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - network

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - network

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - database
    volumes:
      - ./app:/usr/src
    env_file:
      - .env
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  database_data:
