services:
  adminer:
    container_name: adminer
    image: adminer
    restart: on-failure
    ports:
      - "8082:8080"
    depends_on:
      - database
    networks:
      - network
  database:
    image: postgres:16.2-alpine
    restart: always
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - network
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  database_data: