import { Product } from "@/types/product.type";

export const products: Product[] = [
  {
    id: "1",
    name: "Ergonomic Wooden Hat",
    description: "Doloremque et et quia. Quisquam voluptatem et. Quia et et.",
    photo: "https://dummyimage.com/400x400/000/fff",
    price: 30.0,
    type: "hat",
    size: "small",
    gender: "unisex",
    color: "black",
    brand: "Ergonomic Wooden Hat",
  },
  {
    id: "2",
    name: "Cozy Wool Sweater",
    description: "Soft and warm wool sweater for chilly days.",
    photo: "https://dummyimage.com/400x400/000/fff",
    price: 45.0,
    type: "sweater",
    size: "medium",
    gender: "unisex",
    color: "gray",
    brand: "Cozy Wool Sweater",
  },
  {
    id: "3",
    name: "Classic Denim Jeans",
    description: "Timeless denim jeans for everyday wear.",
    photo: "https://dummyimage.com/400x400/000/fff",
    price: 60.0,
    type: "pants",
    size: "large",
    gender: "unisex",
    color: "blue",
    brand: "Classic Denim Jeans",
  },
  {
    id: "4",
    name: "Sporty Sneakers",
    description: "Comfortable and stylish sneakers for active individuals.",
    photo: "https://dummyimage.com/400x400/000/fff",
    price: 70.0,
    type: "shoes",
    size: "small",
    gender: "unisex",
    color: "black",
    brand: "Sporty Sneakers",
  },
  {
    id: "5",
    name: "Casual Hoodie",
    description: "Relaxed and cozy hoodie for casual outings.",
    photo: "https://dummyimage.com/400x400/000/fff",
    price: 35.0,
    type: "hoodie",
    size: "medium",
    gender: "unisex",
    color: "blue",
    brand: "Casual Hoodie",
  },
  {
    id: "6",
    name: "Formal Dress Shirt",
    description: "Elegant dress shirt for formal occasions.",
    photo: "https://dummyimage.com/400x400/000/fff",
    price: 50.0,
    type: "shirt",
    size: "large",
    gender: "men",
    color: "white",
    brand: "Formal Dress Shirt",
  },
  {
    id: "7",
    name: "Leather Jacket",
    description: "Stylish leather jacket for a trendy look.",
    photo: "https://dummyimage.com/400x400/000/fff",
    price: 100.0,
    type: "jacket",
    size: "medium",
    gender: "men",
    color: "black",
    brand: "Leather Jacket",
  },
  {
    id: "8",
    name: "Floral Sundress",
    description: "Beautiful floral sundress for a feminine touch.",
    photo: "https://dummyimage.com/400x400/000/fff",
    price: 65.0,
    type: "dress",
    size: "small",
    gender: "women",
    color: "pink",
    brand: "Floral Sundress",
  },
  {
    id: "9",
    name: "Running Shorts",
    description: "Lightweight and breathable shorts for running.",
    photo: "https://dummyimage.com/400x400/000/fff",
    price: 25.0,
    type: "shorts",
    size: "medium",
    gender: "unisex",
    color: "black",
    brand: "Running Shorts",
  },
  {
    id: "10",
    name: "Striped Polo Shirt",
    description: "Classic striped polo shirt for a preppy look.",
    photo: "https://dummyimage.com/400x400/000/fff",
    price: 40.0,
    type: "shirt",
    size: "large",
    gender: "men",
    color: "blue",
    brand: "Striped Polo Shirt",
  },
  {
    id: "11",
    name: "Vintage Sunglasses",
    description: "Stylish vintage sunglasses for a retro look.",
    photo: "https://dummyimage.com/400x400/000/fff",
    price: 55.0,
    type: "accessory",
    size: "one size",
    gender: "unisex",
    color: "brown",
    brand: "Vintage Sunglasses",
  },
  {
    id: "12",
    name: "Cozy Slippers",
    description: "Warm and comfortable slippers for indoor use.",
    photo: "https://dummyimage.com/400x400/000/fff",
    price: 20.0,
    type: "shoes",
    size: "medium",
    gender: "unisex",
    color: "gray",
    brand: "Cozy Slippers",
  },
  {
    id: "13",
    name: "Graphic T-Shirt",
    description: "Cool graphic t-shirt for a casual look.",
    photo: "https://dummyimage.com/400x400/000/fff",
    price: 30.0,
    type: "shirt",
    size: "medium",
    gender: "unisex",
    color: "black",
    brand: "Graphic T-Shirt",
  },
];
